-- liquibase formatted sql

-- changeset vote_service:1
-- Create vote_type enum if it doesn't exist
DO $$ BEGIN
    CREATE TYPE vote_type AS ENUM ('UPVOTE', 'DOWNVOTE');
EXCEPTION
    WHEN duplicate_object THEN null;
END $$;

-- changeset vote_service:2
-- Create votes table if it doesn't exist
CREATE TABLE IF NOT EXISTS votes (
   vote_id int4 GENERATED BY DEFAULT AS IDENTITY
       (INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
   user_id int4 NOT NULL,
   salary_submission_id int4 NOT NULL,
   vote_type vote_type NOT NULL,
   created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

   CONSTRAINT pk_votes PRIMARY KEY (vote_id),

   CONSTRAINT fk_votes_user
       FOREIGN KEY (user_id)
           REFERENCES users(user_id)
           ON DELETE CASCADE,

   CONSTRAINT fk_votes_salary_submission
       FOREIGN KEY (salary_submission_id)
           REFERENCES salary_submissions(salary_submission_id)
           ON DELETE CASCADE,

   CONSTRAINT unique_user_submission_vote
       UNIQUE (user_id, salary_submission_id)
);

-- changeset vote_service:3
-- Create index on salary_submission_id for faster vote counting
CREATE INDEX IF NOT EXISTS idx_votes_salary_submission_id 
ON votes(salary_submission_id);

-- changeset vote_service:4
-- Create index on vote_type for faster filtering
CREATE INDEX IF NOT EXISTS idx_votes_vote_type 
ON votes(vote_type);

-- changeset vote_service:5
-- Create composite index for vote counting queries
CREATE INDEX IF NOT EXISTS idx_votes_submission_type 
ON votes(salary_submission_id, vote_type);
