version: "3.9"

x-db-env: &db-env
  SPRING_DATASOURCE_URL: ${DB_URL}
  SPRING_DATASOURCE_USERNAME: ${DB_USERNAME}
  SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}

services:

  salary-submission-service:
    build: ./salary_submission_service
    container_name: salary-submission-service
    ports:
      - "8081:8081"
    environment:
      <<: *db-env


  bff-service:
    build: ./bff_service
    container_name: bff-service
    ports:
      - "8082:8082"
    environment:
      <<: *db-env
      SALARY_SUBMISSION_SERVICE_URL: ${SALARY_SUBMISSION_SERVICE_URL}
      VOTE_SERVICE_URL: ${VOTE_SERVICE_URL}
      SEARCH_SERVICE_URL: ${SEARCH_SERVICE_URL}
      STATS_SERVICE_URL: ${STATS_SERVICE_URL}
      IDENTITY_SERVICE_URL: ${IDENTITY_SERVICE_URL}

  vote-service:
    build: ./vote_service
    container_name: vote-service
    ports:
      - "8083:8083"
    environment:
      <<: *db-env
      SALARY_SUBMISSION_SERVICE_URL: ${SALARY_SUBMISSION_SERVICE_URL}
      IDENTITY_SERVICE_URL: ${IDENTITY_SERVICE_URL}

  search-service:
    build: ./search_service
    container_name: search-service
    ports:
      - "8084:8084"
    environment:
      <<: *db-env

  stats-service:
    build: ./stats_service
    container_name: stats-service
    ports:
      - "8085:8085"
    environment:
      <<: *db-env

  identity-service:
    build: ./identity_service
    container_name: identity-service
    ports:
      - "8086:8086"
    environment:
      <<: *db-env

  frontend-service:
    build:
      context: ./frontend_service
      args:
        BFF_SERVICE_URL: ${BFF_SERVICE_URL}
        EXCHANGE_API: ${EXCHANGE_API}
        COUNTRIES_API: ${COUNTRIES_API}
        JOB_ROLES_API: ${JOB_ROLES_API}
    container_name: frontend-service
    ports:
      - "3000:80"
    depends_on:
      - salary-submission-service
      - search-service
      - identity-service
      - vote-service
      - stats-service

