version: "3.9"

x-db-env: &db-env
  SPRING_DATASOURCE_URL: ${DB_URL}
  SPRING_DATASOURCE_USERNAME: ${DB_USERNAME}
  SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}

services:

  salary-submission-service:
    image: ${DOCKER_REPO}/salary-submission-service:latest
    platform: linux/amd64
    container_name: salary-submission-service
    ports:
      - "8081:8081"
    environment:
      <<: *db-env

  bff-service:
    image: ${DOCKER_REPO}/bff-service:latest
    platform: linux/amd64
    container_name: bff-service
    ports:
      - "8082:8082"
    environment:
      <<: *db-env
      SALARY_SUBMISSION_SERVICE_URL: ${SALARY_SUBMISSION_SERVICE_URL}
      VOTE_SERVICE_URL: ${VOTE_SERVICE_URL}
      SEARCH_SERVICE_URL: ${SEARCH_SERVICE_URL}
      STATS_SERVICE_URL: ${STATS_SERVICE_URL}
      IDENTITY_SERVICE_URL: ${IDENTITY_SERVICE_URL}

  vote-service:
    image: ${DOCKER_REPO}/vote-service:latest
    platform: linux/amd64
    container_name: vote-service
    ports:
      - "8083:8083"
    environment:
      <<: *db-env
      SALARY_SUBMISSION_SERVICE_URL: ${SALARY_SUBMISSION_SERVICE_URL}
      IDENTITY_SERVICE_URL: ${IDENTITY_SERVICE_URL}

  search-service:
    image: ${DOCKER_REPO}/search-service:latest
    platform: linux/amd64
    container_name: search-service
    ports:
      - "8084:8084"
    environment:
      <<: *db-env

  stats-service:
    image: ${DOCKER_REPO}/stats-service:latest
    platform: linux/amd64
    container_name: stats-service
    ports:
      - "8085:8085"
    environment:
      <<: *db-env

  identity-service:
    image: ${DOCKER_REPO}/identity-service:latest
    platform: linux/amd64
    container_name: identity-service
    ports:
      - "8086:8086"
    environment:
      <<: *db-env

  frontend-service:
    image: ${DOCKER_REPO}/frontend-service:latest
    platform: linux/amd64
    container_name: frontend-service
    ports:
      - "3000:80"
    environment:
      VITE_API_BASE_URL: ${VITE_API_BASE_URL}
      VITE_EXCHANGE_API: ${VITE_EXCHANGE_API}
      VITE_COUNTRIES_API: ${VITE_COUNTRIES_API}
      VITE_JOB_ROLES_API: ${VITE_JOB_ROLES_API}
    depends_on:
      - bff-service
      - salary-submission-service
      - search-service
      - identity-service
      - vote-service
      - stats-service