apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: app
type: Opaque
stringData:
  JWT_SECRET: Bt1kO1eTLttH6LTH4n6fTXHQJe5rRKmeM3ImURRCIovmFPCER6iryI1ooGbP7PZ3h9rhDNT34SxYs3I9cKiInw==