CREATE TYPE salary_status_enum AS ENUM (
    'PENDING',
    'APPROVED',
    'REJECTED'
);

CREATE TYPE experience_level_enum AS ENUM (
    'JUNIOR',
    'MID',
    'SENIOR',
    'LEAD'
);

CREATE TABLE salary (
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	company varchar(255) NOT NULL,
	country varchar(255) NOT NULL,
	"role" varchar(255) NOT NULL,
	salary numeric(38, 2) NOT NULL,
	submitted_at timestamp(6) NOT NULL,
	years_of_experience int4 NOT NULL,
	currency varchar(255) NULL,
	experience_level zalary.experience_level_enum NOT NULL,
	status zalary.salary_status_enum DEFAULT 'PENDING'::zalary.salary_status_enum NOT NULL,
	anonymize bool DEFAULT false NOT NULL,
	CONSTRAINT salary_pkey PRIMARY KEY (id)
);