spring.application.name=vote_service
server.port=8083

# PostgreSQL datasource
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=false
spring.jpa.hibernate.ddl-auto=none


# Voting Configuration
vote.approval.threshold=5
vote.rejection.threshold=3

# Service URLs
salary.submission.service.url=${SALARY_SUBMISSION_SERVICE_URL}
identity.service.url=${IDENTITY_SERVICE_URL}

# Logging
logging.level.lk.zalary.vote_service=DEBUG
logging.level.org.liquibase=DEBUG
