apiVersion: v1
kind: ConfigMap
metadata:
  name: bff-config
  namespace: app
data:
  SALARY_SERVICE_URL: "http://salary-submission-service:8081"
  VOTE_SERVICE_URL: "http://vote-service:8083"
  SEARCH_SERVICE_URL: "http://search-service:8084"
  STATS_SERVICE_URL: "http://stats-service:8085"
  IDENTITY_SERVICE_URL: "http://identity-service:8086"
  REPORT_SERVICE_URL: "http://report-service:8087"
