apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
data:
  VITE_API_BASE_URL: "http://bff-service:8082"
  VITE_EXCHANGE_API: "https://open.er-api.com/v6/latest/USD"
  VITE_COUNTRIES_API: "https://restcountries.com/v3.1/all?fields=name"
  VITE_JOB_ROLES_API: "https://raw.githubusercontent.com/jneidel/job-titles/master/job-titles.json"
