apiVersion: v1
kind: ConfigMap
metadata:
  name: service-config
  namespace: app
data:
  JWT_EXPIRATION: "3600000"
  SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres-service.data.svc.cluster.local:5432/zalary"
  SPRING_DATASOURCE_USERNAME: "postgres"
  DB_NAME: "zalary"
  SPRING_DATASOURCE_PASSWORD: "postgres"
  SALARY_SUBMISSION_SERVICE_URL: "http://salary-submission-service:8081"
  IDENTITY_SERVICE_URL: "http://identity-service:8086"