-- liquibase formatted sql

-- changeset report_service:1
CREATE TABLE IF NOT EXISTS reports (
   report_id int4 GENERATED BY DEFAULT AS IDENTITY
       (INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
   user_id int4 NOT NULL,
   salary_submission_id int4 NOT NULL,
   reason TEXT,
   created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

   CONSTRAINT pk_reports PRIMARY KEY (report_id),

   CONSTRAINT fk_reports_user
       FOREIGN KEY (user_id)
           REFERENCES users(user_id)
           ON DELETE CASCADE,

   CONSTRAINT fk_reports_submission
       FOREIGN KEY (salary_submission_id)
           REFERENCES salary_submissions(salary_submission_id)
           ON DELETE CASCADE,

   CONSTRAINT unique_user_submission_report
       UNIQUE (user_id, salary_submission_id)
);

-- changeset report_service:2
CREATE INDEX IF NOT EXISTS idx_reports_salary_submission_id
ON reports(salary_submission_id);
