spring.application.name=bff_service
server.port=8082

salary.submission.service.url=${SALARY_SUBMISSION_SERVICE_URL}
vote.service.url=${VOTE_SERVICE_URL}
search.service.url=${SEARCH_SERVICE_URL}
stats.service.url=${STATS_SERVICE_URL}
identity.service.url=${IDENTITY_SERVICE_URL}
report.service.url=${REPORT_SERVICE_URL}

#health check
management.endpoints.web.exposure.include=health