apiVersion: apps/v1
kind: Deployment
metadata:
  name: identity-service
  namespace: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: identity-service
  template:
    metadata:
      labels:
        app: identity-service
    spec:
      containers:
        - name: identity-service
          image: samalrandula/identity-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8086
          envFrom:
            - configMapRef:
                name: service-config
            - secretRef:
                name: app-secret
            
