apiVersion: apps/v1
kind: Deployment
metadata:
  name: report-service
  namespace: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: report-service
  template:
    metadata:
      labels:
        app: report-service
    spec:
      containers:
        - name: report-service
          image: sahanr94/report-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8087
          envFrom:
            - configMapRef:
                name: service-config
            
