apiVersion: v1
kind: Service
metadata:
  name: salary-submission-service
  namespace: app
spec:
  type: ClusterIP
  selector:
    app: salary-submission-service
  ports:
    - port: 8081
      targetPort: 8081
